### PR TITLE
Handle newline at start or end of section

### LINKED ISSUE #39: Pressing enter at the start of a line/section has unexpected results
Placing the cursor at the start of a line and pressing `enter` causes the line to move down in 0.2.1. In 0.2.2 it at first appears to do nothing.

If, after having pressed `enter` at the beginning of a line, you move the cursor to somewhere else on the same line and also press `enter`, the content of the line is duplicated before the new line is added.

How I reproduced:

- on master (58ffbc8) using `broccoli serve` to test the demo

Test 1:

- Place the cursor at the beginning of the first line, press `enter` 
- nothing happens
- Place the cursor anywhere except the beginning of the second line, press `enter` 
- the content of the line is duplicated and a new line is added

Test 2:

- Place the cursor at the beginning of the first line, press `enter`
- nothing happens
- Place the cursor anywhere except the beginning of the second line, press `enter`
- a new line is entered and no content is duplicated

Test 3: 

- Place the cursor at the beginning of the first line, press `enter` multiple times
- Place the cursor at the beginning of the second line, press `enter` multiple times
- Place the cursor anywhere except the beginning of a line, press `enter`
- Content is duplicated on both lines!

### PR DESCRIPTION
**Pull request by bantic**
Handle newline at start of section

  * simplify section#splitMarker
  * tests for hitting enter in middle and end of section
  * add test for hitting enter in first section
  * fix bug with PostNodeBuilder not assigning a builder to the blank marker

fixes #39

### CODE REVIEW

File: src/js/editor/editor.js [hunk 1]
```diff
@@ -444,17 +444,26 @@ class Editor {
...
+      afterMarker = beforeMarker;
+      beforeMarker = null;
+    }
+
+    if (beforeMarker) {
+      section.markers.insertAfter(beforeMarker, marker);
+    } else {
+      // start of section, remove the existing marker and add a blank one
+      section.markers.remove(marker);
+      section.markers.append(this.builder.createBlankMarker());
```
Comment (mixonic) [inline src/js/editor/editor.js]: Not needed, but alternatively:

```
section.markers.splice(marker, 1, [this.builder.createBlankMarker()]);
```

Comment (mixonic) [inline src/js/editor/editor.js]: Oh I'm sorry, I misread this. You're removing a marker from some arbitrary place and only appending the blank marker, all the time.

Comment (mixonic) [inline src/js/editor/editor.js]: I'm confused- shouldn't the blank marker be in a new section?

Comment (bantic) [inline src/js/editor/editor.js]: Yeah, agreed, this is fairly confusing. I'm reworking this to be a bit more declarative.

**Comment by bantic** [comment]
hold off on merging for the moment. I'm reworking `Marker.split` and the way `Section` uses it, which will hopefully make this a simpler operation to code (and the code simpler to read).

**Comment by bantic** [comment]
@mixonic this is ready now if you want to look it over

File: src/js/models/markup-section.js [hunk 2]
```diff
@@ -53,16 +58,57 @@ export default class Section extends LinkedItem {
...
+
+  /**
+   * Remove extranous empty markers, adding one at the end if there
+   * are no longer any markers
+   *
+   * Mutates this section's markers
+   */
+  coalesceMarkers() {
+    forEach(
+      filter(this.markers, m => m.empty()),
```
Comment (mixonic) [inline src/js/models/markup-section.js]: `m.empty` should probably be `m.isEmpty`

Also doing a filter only to pass it to another iterator seems wasteful- this could be done in a single pass with an `if`

Comment (mixonic) [inline src/js/models/markup-section.js]: changed the loop on master, we can ponder `empty`

Comment (bantic) [inline src/js/models/markup-section.js]: @mixonic removing markers while iterating them causes the iteration to skip (`item.next` is something different before/after the callback). I have a PR coming to fix iteration of the linkedlist
